import pandas as pd

# Lista de palabras principales y sus sinónimos
data = {
    'main_word': [
        'pasto', 'cielo', 'amanecer', 'noche', 'mar', 'bosque', 'desierto', 'puesta de sol',
        'invierno', 'primavera', 'verano', 'otoño', 'lago', 'montaña', 'ciudad', 'campo',
        'amanecer', 'anochecer', 'otoño', 'invierno', 'verano', 'primavera', 'noche', 'día',
        'mediodía', 'atardecer', 'aurora', 'bosque', 'desierto', 'playa', 'mar', 'océano',
        'río', 'lago', 'montaña', 'valle', 'ciudad', 'campo', 'jardín', 'parque',
        'pasto', 'césped', 'flor', 'árbol', 'hoja', 'nieve', 'hielo', 'roca',
        'arena', 'tierra', 'barro', 'sol', 'luna', 'estrella', 'nube', 'lluvia',
        'tormenta', 'arco iris', 'fuego', 'lava', 'volcán', 'selva', 'cascada', 'cueva',
        'costa', 'isla', 'duna', 'pantano', 'cielo', 'pradera', 'pueblo', 'aldea',
        'puerto', 'muelle', 'glaciar', 'tundra', 'sabana', 'cañón', 'acantilado', 'plano',
        'chaparrón', 'neblina', 'bruma', 'granizo', 'huracán', 'tifón', 'ciclón', 'tornado',
        'tempestad', 'nevazón', 'ventisca', 'llovizna', 'chubasco', 'aguanieve', 'rocío', 'resplandor',
        'claridad', 'penumbra', 'oscuridad', 'negrura', 'brillo', 'fulgor', 'centella', 'chispa',
        'resplandecer', 'crepúsculo', 'penumbra', 'anochecer', 'desvanecerse', 'alba', 'brillo', 'sombra',
        'transparencia', 'opacidad', 'relucir', 'brillar', 'refulgir', 'destellar', 'resplandecer', 'relumbrar',
        'fulgurar', 'centellar', 'iris', 'prisma', 'saturación', 'luminosidad', 'intensidad', 'tono',
        'matiz', 'croma', 'sombra', 'espectro', 'gama', 'gradiente', 'degradado', 'coloración',
        'pigmento', 'tinte', 'tonalidad', 'colorete', 'pigmentar', 'pintar', 'teñir', 'acarminar',
        'amapolar', 'azular', 'enverdecer', 'encarnar', 'amarillear', 'ocrear', 'blanquear', 'negrear',
        'grisar', 'platear', 'dorar', 'broncear', 'cobriar', 'rubí', 'esmeralda', 'zafiro',
        'ámbar', 'jade', 'coral', 'turquesa', 'topacio', 'granate', 'rubí', 'lapislázuli',
        'púrpura', 'violeta', 'añil', 'índigo', 'lavanda', 'lila', 'malva', 'ciruela',
        'magenta', 'rosa', 'fucsia', 'carmesí', 'rojo', 'bermellón', 'anaranjado', 'naranja',
        'coral', 'albaricoque', 'melocotón', 'oro', 'amarillo',  'crema', 'marfil', 'blanco', 'perla', 'gris', 'ceniza', 'carbón', 'negro',
        'ébano', 'azul', 'celeste', 'turquesa', 'aguamarina', 'verde', 'esmeralda', 'oliva',
        'lima', 'menta', 'verde botella', 'verde musgo', 'verde pino', 'café', 'marrón', 'castaño',
        'chocolate', 'caoba', 'teca', 'madera', 'nogal', 'almendra', 'avellana', 'miel',
        'ámbar', 'bronce', 'latón', 'cobre', 'roble', 'pino',  'caoba'
    ],
    'synonyms': [
        'hierba, césped, gramilla', 'firmamento, cielo azul, bóveda celeste', 'alborada, madrugada, primera luz',
        'anochecer, oscuridad, medianoche', 'océano, marino, costa', 'selva, foresta, arboleda', 'arenal, páramo, erial', 'ocaso, crepúsculo, sol poniente',
        'estación fría, hibernación, época invernal', 'florecimiento, estación de las flores, renacimiento', 'estación cálida, verano boreal, época estival', 'caída de las hojas, estación otoñal, temporada de otoño',
        'estanque, embalse, laguna', 'sierra, cordillera, cumbre', 'metrópoli, urbe, villa', 'pradera, terreno, zona rural',
        'alborada, amanecida, alba', 'ocaso, anochecida, atardecer', 'fall, estación de otoño, estación de la cosecha', 'hibernación, época de frío, estación invernal',
        'verano boreal, época de calor, estación estival', 'estación de las flores, renacimiento, primavera', 'anochecer, oscuridad, medianoche', 'jornada, luz diurna, período diurno',
        'hora de almuerzo, mediodía soleado, cenit', 'ocaso, crepúsculo, sol poniente', 'alba, aurora boreal, primera luz',
        'selva, foresta, arboleda', 'arenal, páramo, erial', 'costa, litoral, orilla', 'océano, marino, costa', 'mar profundo, gran azul, aguas oceánicas',
        'corriente, arroyo, caudal', 'estanque, embalse, laguna', 'sierra, cordillera, cumbre', 'vallecito, depresión, planicie',
        'metrópoli, urbe, villa', 'pradera, terreno, zona rural', 'huerto, vergel, jardín botánico', 'jardinera, parque urbano, zona verde',
        'hierba, césped, gramilla', 'césped, hierba, gramilla', 'florecilla, flor silvestre, capullo', 'plantón, arbusto, fronda', 'hojuela, fronda, follaje',
        'escarcha, copo de nieve, ventisca', 'carámbano, congelación, hielo compacto', 'peñasco, pedrusco, guijarro',
        'polvareda, arenisca, dunas', 'terruño, terrón, suelo', 'fango, lodo, barro', 'astro rey, estrella solar, solsticio', 'satélite, astro lunar, menguante',
        'constelación, astro, lucero', 'nubarrón, nubecilla, cúmulo', 'precipitación, chubasco, aguacero',
        'tempestad, ciclón, tormentón', 'arco cromático, arco de colores, arco irisado', 'llama, incendio, combustión', 'magma, roca fundida, flujo volcánico',
        'montaña de fuego, cráter, cono volcánico', 'jungla, mata, bosque tropical', 'catarata, salto de agua, torrente', 'gruta, caverna, antro',
        'ribera, litoral, franja costera', 'islote, archipiélago, atolón', 'colina de arena, médano, arenal', 'ciénaga, humedal, marisma',
        'firmamento, cielo azul, bóveda celeste', 'dehesa, campiña, pastizal', 'villa, localidad, población', 'aldehuela, villorrio, caserío',
        'embarcadero, dársena, puerto deportivo', 'muellecito, amarradero, espigón', 'casquete glaciar, masa de hielo, iceberg', 'tundración, bioma frío, estepa helada',
        'sabana tropical, llanura, planicie herbosa', 'garganta, desfiladero, quebrada', 'precipicio, farallón, despeñadero', 'planicie, llanura, meseta',
        'chubasco, aguacero, tromba de agua', 'neblinosidad, niebla, calima', 'brumazón, calina, neblina espesa', 'granizada, pedrisco, nieve granulada',
        'ciclón tropical, tormenta, temporal', 'tifonada, ciclón asiático, huracanada', 'tormenta tropical, ciclón, huracanada', 'ciclón, tromba, huracán',
        'temporal, borrasca, tormenta', 'ventisca, nevada, tormenta de nieve', 'tormenta de nieve, ventisca, nevada intensa', 'llovizna ligera, calabobos, lluvia menuda',
        'chaparrón, aguacero, tromba de agua', 'agua-nieve, lluvia y nieve, nieve líquida', 'rocío de la mañana, escarcha, orvallo', 'luminosidad, fulgor, brillo',
        'luz, claridad, resplandor', 'semioscuridad, crepúsculo, entreluz', 'tinieblas, penumbra, umbría', 'negrura, sombra, oscuridad',
        'destello, centelleo, resplandor', 'resplandor, fulgor, destello', 'chispa, relámpago, destello', 'chisporroteo, relámpago, destello',
        'brillar, fulgurar, relucir', 'crepúsculo, anochecer, ocaso', 'penumbra, semioscuridad, entreluz', 'ocaso, anochecida, atardecer',
        'desaparecer, disolverse, desintegrarse', 'aurora, alborada, amanecer', 'resplandor, fulgor, destello', 'sombra, penumbra, oscuridad',
        'claridad, diafanidad, transparencia', 'opacidad, falta de transparencia, mate', 'brillar, destellar, relumbrar',
        'brillar, fulgurar, destellar', 'relumbrar, brillar, resplandecer', 'relumbrar, fulgurar, centellear', 'relumbrar, brillar, resplandecer',
        'fulgurar, destellar, brillar', 'brillar, relumbrar, centellear', 'arco iris, espectro de luz, círculo cromático', 'cristal, vidrio, prisma óptico',
        'vividez, saturación de color, intensidad de color', 'luminosidad, claridad, brillo', 'intensidad de color, saturación, vivacidad', 'tinte, matiz, color',
        'matiz, tinte, coloración', 'croma, intensidad, pureza del color', 'oscurecimiento, sombreado, penumbra', 'espectro de color, gama cromática, arco iris',
        'gama cromática, escala de colores, espectro', 'gradiente de color, degradado, transición de color', 'degradado de color, gradiente, transición de tonos',
        'coloración, tinte, matiz', 'pigmento, tinte, colorante', 'tinte, color, matiz', 'tonalidad, matiz, tinte', 'rubor, color, matiz',
        'pigmentar, teñir, colorear', 'pintar, colorar, colorear', 'teñir, colorear, tintar', 'acarminar, enrojecer, sonrosar',
        'tintar, teñir de rojo, colorear', 'azular, teñir de azul, colorear de azul', 'verdear, teñir de verde, colorear de verde', 'encarnarse, enrojecer, colorear de rojo',
        'amarillear, volverse amarillo, teñir de amarillo', 'ocrear, colorear de ocre, teñir de ocre', 'blanquear, encalar, emblanquecer', 'ennegrecer, oscurecer, tiznar',
        'grisar, volverse gris, oscurecerse', 'platear, argentar, pintar de plata', 'dorar, hacer dorado, pintar de dorado', 'broncear, hacer de bronce, pintar de bronce',
        'cobriar, hacer de cobre, pintar de cobre', 'rubí, rojo intenso, carmesí', 'esmeralda, verde brillante, verde esmeralda', 'zafiro, azul intenso, azul zafiro',
        'ámbar, amarillo dorado, dorado', 'jade, verde jade, verde intenso', 'coral, rosado, rosa coral', 'turquesa, azul verdoso, verde azulado',
        'topacio, amarillo topacio, dorado', 'granate, rojo oscuro, carmesí', 'rubí, rojo intenso, carmesí', 'lapislázuli, azul profundo, azul lapislázuli',
        'púrpura, morado, violeta', 'violeta, morado, lila', 'añil, índigo, azul profundo', 'índigo, azul oscuro, azul profundo',
        'lavanda, lila, violeta claro', 'lila, lavanda, violeta claro', 'malva, lila, lavanda', 'ciruela, violeta oscuro, morado',
        'magenta, fucsia, rosa oscuro', 'rosa, rosado, rosáceo', 'fucsia, magenta, rosa fuerte', 'carmesí, rojo intenso, escarlata',
        'rojo, carmesí, escarlata', 'bermellón, rojo vivo, rojo brillante', 'naranja, anaranjado, color de naranja', 'anaranjado, naranja, color de naranja',
        'coral, rosado, rosa coral', 'albaricoque, durazno, melocotón', 'melocotón, durazno, albaricoque', 'dorado, amarillo dorado, oro',
        'amarillo, dorado, color del sol', 'crema, beige, marfil', 'marfil, blanco hueso, blanco cremoso', 'blanco, níveo, albino',
        'perla, blanco perlado, blanco nacarado', 'gris, plomizo, ceniza', 'ceniza, grisáceo, gris claro', 'carbón, negro carbón, negro intenso',
        'negro, azabache, ébano', 'ébano, negro intenso, negro profundo', 'azul, celeste, azul marino', 'celeste, azul cielo, azul claro',
        'turquesa, verde azulado, azul verdoso', 'aguamarina, azul verdoso, verde azulado', 'verde, esmeralda, verde intenso', 'verde esmeralda, verde brillante, verde',
        'oliva, verde oliva, verde militar', 'lima, verde lima, verde claro', 'menta, verde menta, verde claro', 'verde botella, verde oscuro, verde intenso',
        'verde musgo, verde oscuro, verde musgoso', 'verde pino, verde oscuro, verde intenso', 'café, marrón, chocolate', 'marrón, café, castaño',
        'castaño, marrón, café', 'chocolate, marrón oscuro, marrón chocolate', 'caoba, marrón rojizo, marrón caoba', 'teca, marrón claro, marrón teca',
        'madera, color madera, marrón madera', 'nogal, marrón oscuro, marrón nogal', 'almendra, marrón claro, color almendra', 'avellana, marrón claro, color avellana',
        'miel, ámbar, dorado', 'ámbar, dorado, amarillo', 'bronce, marrón bronce, dorado', 'latón, dorado, amarillo dorado', 'cobre, marrón rojizo, marrón cobre',
        'roble, marrón claro, color roble', 'pino, verde pino, verde oscuro', 'abeto, verde oscuro, verde abeto', 'caoba, marrón rojizo, marrón caoba'
    ]
}

df = pd.DataFrame(data)
df.to_csv('synonyms.csv', index=False)
